### ISSUE TITLE
Convert SVG to PNG work on local machine but fails on Azure Web Services

### ISSUE THREAD

**Issue by centDejan** [dlemstra/Magick.NET#55]
I am using Magick.NET to convert SVG to PNG. It works really well on local machine, but when I publish the project to Azure it fails to render PNG.

I have created simple web page to demonstrate the issue. You can check http://adforcent-staging.azurewebsites.net/test/convert to see the result of the input SVG (in textarea).

On local machine the code produces readable image (same as when I open SVG with Inkscape), but when the code is published, I do not see any text.

I am struggling for couple of days and with no progress. I cannot find any similar issues with Google.

Code is simple:

string svg = form["svg"]; // SVG from the form

byte[] SvgBytes = Encoding.ASCII.GetBytes(svg);
MagickReadSettings readSettings = new MagickReadSettings()
	{
		Format = MagickFormat.Svg,
	};

using (MagickImage image = new MagickImage(SvgBytes, readSettings))
	{
		image.Format = MagickFormat.Png;
		result = image.ToBitmap();
	}

![result_local](https://cloud.githubusercontent.com/assets/6339317/26578896/f9c38e5e-4531-11e7-9a28-a9c74244d3fa.JPG)
![result_azure](https://cloud.githubusercontent.com/assets/6339317/26578895/f9c1006c-4531-11e7-8254-0d18498f4942.JPG)

Am I the only one with this problems? I am using latest version of Magick.net (v7).

I would appreciate any hint on that subject.

Thank you in advance!

**Comment by dlemstra** [comment]
It looks like your issue is resolved? Did you change anything to your azure site? I saw it fail 2 weeks ago.

**Comment by centDejan** [comment]
The issue is not resolved, but I least know the reason. Azure 'Web
Services' do not support GDI+ and I assume Magic.NET depends on it. What I
did is to write a service and host it on Azure VM, where there is no
limitation for GDI+ support.

Best regards, Dejan

**Comment by dlemstra** [comment]
We use librsvg to read SVG files and this library uses GDI+. Thanks for letting me know why it failed. I don't think that we can fix this.

**Comment by mchenx** [comment]
@centDejan pls check my issue [https://github.com/dlemstra/Magick.NET/issues/72](url)
I deployed a simple web app service, one of the API generates jpeg on the fly, and it totally uses GDI+
You can call [http://testfontgdi.azurewebsites.net/api/values/6?text=yourstring](url) and see how it responses,  you may also replace yourstring with strings you like
