### ISSUE TITLE
Apng - Error delegate failed ffmpeg

### ISSUE THREAD

**Issue by alaw-lufc** [dlemstra/Magick.NET#777]
Hi,

I am trying to use Magick.Net (v7.22.1) to build an animated png (apng) file in VB.net. 

I have copied the latest ffmpeg.exe to the bin folder and am trying to adapt the gif example code (https://github.com/dlemstra/Magick.NET/blob/master/docs/CombiningImages.md) to output a apng file by adjusting the .Write line to something like;

collection.Write("Snakeware.apng", MagickFormat.APng)

I keep getting an error;
delegate failed `"ffmpeg.exe" -nostdin -v -1 -i "%M%%d.pam" -plays %I "%u.%m" 2> "%u"' @ error/delegate.c/InvokeDelegate/1898

I appreciate i am probably missing something obvious, but i couldn't find any examples for apng creation so i'm just guessing it would be similar to a gif.

Thanks

**Comment by dlemstra** [comment]
For animate PNG you will need to have the `ffmpeg.exe` file in your `%PATH%`. You can download the binary from here: https://github.com/ImageMagick/ImageMagick-Windows/releases/tag/20200615.

**Comment by alaw-lufc** [comment]
Thanks, got that already though. Without it i get a 'FailedToExecuteCommand' error on ffmpeg rather than the delegate failed message i'm getting.

**Comment by dlemstra** [comment]
It seems that ffmpeg is raising an error when the second frame is written. We will need to investigate this.

**Comment by alaw-lufc** [comment]
Thanks, not an error on my part then - that makes a change!. 
I guess the apng stuff is new in Magick.Net so some teething problems are to be expected. For now i've switched to apng assembler CLI version (https://sourceforge.net/projects/apngasm/) and call that instead.

**Comment by dlemstra** [comment]
This issue should be resolved in the latest release. Can you give it another try?

**Comment by alaw-lufc** [comment]
Just updated to 7.22.2.2, i still get the same error message as in the first post.

**Comment by dlemstra** [comment]
I can no longer reproduce your issue. Are you sure that `ffmpeg.exe` is in your `%PATH`?

**Comment by alaw-lufc** [comment]
I did some further tests, when i retested last time at some stage i'd changed the file extension of the output to .png
e.g. collection.Write("Snakeware.png", MagickFormat.APng)
That errors as above, but if i change to 
collection.Write("Snakeware.apng", MagickFormat.APng)
and it works in 7.22.2.2!

So this is resolved. Thanks.
